#!/bin/bash -l
#PBS -l nodes=4:ppn=8
#PBS -l walltime=00:02:00
#PBS -l mem=20mb
#PBS -j oe
#PBS -N bitonic
#PBS -o bitonic_out.txt

echo "Running job on host '$HOST' - " `date`
mpirun -np 9 ./$1
echo "...done"